plugins {
	id 'java'
	id 'org.springframework.boot' version '4.1.1'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.the.flagship.jdt'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

repositories {
	mavenCentral()
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	implementation 'org.springframework.boot:spring-boot-starter-web'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
	implementation 'org.apache.pdfbox:pdfbox:3.0.8'
	implementation platform("org.springframework.ai:spring-ai-bom:2.0.0")
 	 // Replace the following with the specific module dependencies (e.g., spring-ai-openai) or starter modules (e.g., spring-ai-starter-model-openai) that you wish to use
  	// implementation 'org.springframework.ai:spring-ai-openai'
	implementation 'org.springframework.ai:spring-ai-starter-model-openai'   

}

tasks.named('test') {
	useJUnitPlatform()
}
tasks.named('bootRun') {
    // no systemProperty for app.file-read.enabled here
}

tasks.register('runFileRead') { // <-- we register command line runner as task we can execute later
    dependsOn 'bootRun'
	 // Accept a -PbootArgs="..." flag - if we want to isolate CLR from bootapplication, we require this to be regocnized as "args"
	// doFirst {
    //     def a = project.findProperty('bootArgs')
    //     if (a) {
    //         tasks.named('bootRun', JavaExec) {
    //             args a.split(' ')
    //         }
    //     }
    // }
}

tasks.register('runPdfFileReadWithPdfbox') { 
    dependsOn 'bootRun'
}

tasks.register('runPdfFileReadWithPdfBox') { 
    dependsOn 'bootRun'
}

tasks.register('runChat', JavaExec) {
    dependsOn 'classes'
    classpath = sourceSets.main.runtimeClasspath
    mainClass = 'com.the.flagship.jdt.flagship.FlagshipApplication'
	systemProperty 'app.runner', 'simple-chat-batch'
    standardInput = System.in
}

gradle.taskGraph.whenReady { graph -> //<- this basically says, if task is ready, append the properties.
    if (graph.hasTask(':runFileRead')) {
        tasks.named('bootRun', JavaExec) {
			systemProperty 'app.runner', 'sample-clr'
			//instead of the do first we add it here since its bugging, array is empty if done on dofirst
			def a = project.findProperty('bootArgs')
            if (a) {
                args a.split(' ')
            }
        }
    }

	if (graph.hasTask(':runPdfFileRead')) {
		tasks.named('bootRun', JavaExec) {
			systemProperty 'app.runner', 'pdf-java'
            // systemProperty 'app.file-read.enabled', 'true'
			//instead of the do first we add it here since its bugging, array is empty if done on dofirst
			def filePath = project.findProperty('filePath')
			args filePath
        }
	}
	
	if (graph.hasTask(':runPdfFileReadWithPdfbox')) {
		tasks.named('bootRun', JavaExec) {
			systemProperty 'app.runner', 'pdf-box'
            // systemProperty 'app.file-read.enabled', 'true'
			//instead of the do first we add it here since its bugging, array is empty if done on dofirst
			def filePath = project.findProperty('filePath')
			args filePath
        }
	}


}